### ISSUE TITLE
Questions regarding VCF file and output files

### ISSUE THREAD

**Issue by wbf520qcp** [sridnona/10x_singlecell#15]
I'm trying to run cb_sniffer using some test data from varTrix and got a couple of questions:
(1) The output files contain nothing but a header row. I wonder if if the reference genome used to call variants matters here as the VCF file I used is based on GRCh 37.

(2)Is there a detailed description of output files?

Thanks for help
Bofei

**Comment by sridhar0605** [comment]
Hi @wbf520qcp , 
are your variant calls from the same bam/cram?

Reference is not required as an input for cb_sniffer..

Thanks

**Comment by wbf520qcp** [comment]
Hi, thanks for replying. The bam file is from single cell data and the variant calls are from targeted gene sequencing that we are interested in. My understanding is cb_sniffer will determine whether each barcode contains those pre-defined variants, right? 

> Hi @wbf520qcp , are your variant calls from the same bam/cram?
> 
> Reference is not required as an input for cb_sniffer..
> 
> Thanks

**Comment by sridhar0605** [comment]
Yes that is correct,  did you use the same reference for both of them?

**Comment by wbf520qcp** [comment]
The reference is the same. Then I got this error message
Traceback (most recent call last):
  File "/rsrch3/scratch/canmed_fell_prog/haabbas/BofeiWang/Mutation_detect/cb_sniffer/cb_sniffer.py", line 391, in <module>
    barcode_counts = x.count_barcodes(bam_file, bars, x.classify(), mq, bq)
  File "/rsrch3/scratch/canmed_fell_prog/haabbas/BofeiWang/Mutation_detect/cb_sniffer/cb_sniffer.py", line 86, in count_barcodes
    truncate=True, stepper="nofilter", max_depth=100000000):
  File "pysam/libcalignmentfile.pyx", line 1330, in pysam.libcalignmentfile.AlignmentFile.pileup
  File "pysam/libchtslib.pyx", line 686, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `1`

**Comment by sridhar0605** [comment]
Could you please head few lines of your variant table and bam file,

**Comment by wbf520qcp** [comment]
<img width="502" alt="Screen Shot 2022-03-25 at 12 01 56 PM" src="https://user-images.githubusercontent.co
<img width="1377" alt="Screen Shot 2022-03-25 at 12 10 10 PM" src="https://user-images.githubusercontent.com/56213252/160168631-ab5630ac-c44b-44bc-8611-27b4a70b4448.png">
m/56213252/160167456-f4fc09fe-f64d-412e-856f-c8e793743d49.png">

here you go

**Comment by wbf520qcp** [comment]
<img width="502" alt="Screen Shot 2022-03-25 at 12 01 56 PM" src="https://user-images.githubusercont
<img width="1377" alt="Screen Shot 2022-03-25 at 12 10 10 PM" src="https://user-images.githubusercontent.com/56213252/160169077-87def2c5-6158-43e1-b75a-1d02ca6e1c80.png">
ent.com/56213252/160169071-b19a1ad2-2ace-44ce-8a47-4459cfa2371c.png">
here you go

**Comment by wbf520qcp** [comment]
<img width="502" alt="Screen Shot 2022-03-25 at 12 01 56 PM" src="https://user-images.githubusercontent.com/56213252/160169115-762d090b-350f-42e3-a26a-76567e8b7ae7.png">

**Comment by sridhar0605** [comment]
So you have `chr1` prefix in your bam but not in the variant table `1`.

Please add the prefix to the variant table

**Comment by wbf520qcp** [comment]
That worked. But mutations were detected in very few cells (most abundant one was found in 137 cells out of >6000; no indwells were detected). Curious whether it's because of the sequencing depth? Or is there any parameter in the code I can tune to increase the sensitivity?

**Comment by sridhar0605** [comment]
There is nothing that you can do to increase the number of cell,  so yes the depth seems to be lower...if i had to guess..

**Comment by wbf520qcp** [comment]
Ok, thank you.
